# -*- coding: utf-8 -*-
"""Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SKc61CKdOaw9I5lyIuINyAOwHhKZTWxt
"""

#Q3--------------------------------------------------------------------------------
def computeGCD(x, y):

  x = toPositive(int(x))
  y = toPositive(int(y))
  
  if x > y: 
      small = y 
  else: 
      small = x 
  for i in range(1, small+1): 
      if((x % i == 0) and (y % i == 0)): 
          gcd = i 
              
  return gcd 

def toPositive(y): 
 if(y <0):
   y = (-1) * y
 return y

def compute(x, y): 
  gcd = computeGCD(x,y)
  new_x = x / gcd
  new_y = y / gcd
  return new_x , new_y

try:
  
  x = 18
  y = 12

  if(y != 0 & y != 'inf' ):
    new_x , new_y = compute(x,y)
    print("("+str(int(compute(x,y)[0]))+","+str(int(compute(x,y)[1]))+")")
  else:
    print("None")
except ValueError:
  print("None")