# -*- coding: utf-8 -*-
"""Q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mM8xvD08Z2kRy_fue6ySBch29uIMx0md
"""

#Q4----------------------------------------------------------------
import random
import numpy
import matplotlib.pyplot as plt

def random_matrix(low ,high ,row , column):
  A = numpy.random.uniform(low, high, size=(row,column))
  print(A)
  plt.plot(A[:,0] , color='red', linestyle='dashed',label = "col1")
  plt.plot(A[:,1] ,'-.', color='blue',label = "col2")
  plt.xlabel('x - axis')
  plt.ylabel('y - axis')  
  plt.title('HW0-P4-9623097') 
  plt.axis('equal')   
  plt.legend()

random_matrix(2,5,3,4)